# Travis-CI file for Espruino

language: c

before_script:
 - source ./scripts/provision.sh $BOARD
 - python --version

after_script:
  - "if [[ -n \"$UPLOADTOKEN\" ]]; then
       ls *.bin *.hex *.tgz *.zip | xargs -I {} curl -v -F \"binary=@{}\" \"http://www.espruino.com/travis_upload.php?commit=$TRAVIS_COMMIT&branch=$TRAVIS_BRANCH&token=$UPLOADTOKEN\";
     fi"
  # upload to an S3 bucket, requires S3_BUCKET, AWS_ACCESS_KEY_ID and AWS_SECRET_KEY to be set
  # in environment using travis' repository settings
  - "if [[ -n \"$S3_BUCKET\" && -n \"$AWS_ACCESS_KEY_ID\" ]]; then
      echo Uploading *.tgz to $S3_BUCKET;
      curl -Ls https://github.com/rlmcpherson/s3gof3r/releases/download/v0.5.0/gof3r_0.5.0_linux_amd64.tar.gz | tar zxf - gof3r_0.5.0_linux_amd64/gof3r;
      mv gof3r*/gof3r .;
      ls *.tgz | xargs -I {} ./gof3r put -b $S3_BUCKET -k espruino/{} --acl public-read -p {};
      ls *.tgz | xargs -I {} echo \"URL: http://$S3_BUCKET/espruino/{}\";
      fi"

compiler:
  - gcc

env:
  global:
    - TRAVIS=1
    - V=0
    - RELEASE=1
  matrix:
    - BOARD=LINUX
    - BOARD=ESPRUINOBOARD PAD_FOR_BOOTLOADER=1
    - BOARD=PICO_R1_3 PAD_FOR_BOOTLOADER=1
    - BOARD=ESPRUINOWIFI PAD_FOR_BOOTLOADER=1
    - BOARD=PUCKJS DFU_UPDATE_BUILD=1
    - BOARD=PIXLJS DFU_UPDATE_BUILD=1
    - BOARD=HEXBADGE DFU_UPDATE_BUILD=1
    - BOARD=MDBT42Q DFU_UPDATE_BUILD=1
    - BOARD=ESP32
    - BOARD=ESP8266_BOARD
    - BOARD=ESP8266_4MB
    - BOARD=MICROBIT
    - BOARD=NRF52832DK
    - BOARD=RUUVITAG DFU_UPDATE_BUILD=1
    - BOARD=WIO_LTE
    - BOARD=THINGY52
    - BOARD=THINGY52 DFU_UPDATE_BUILD=1
    - BOARD=STM32L496GDISCOVERY
    - BOARD=RAK8211
    - BOARD=RAK8212
    - BOARD=EFM32GGSTK

script: make

notifications:
  email: false
